/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-07-21 01:35:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>OnlineShop</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Global styles START -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/font-awesome/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Global styles END -->\r\n");
      out.write("\r\n");
      out.write("<!-- Page level plugin styles START -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/fancybox/source/jquery.fancybox.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("<!-- for slider-range -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/bxslider/jquery.bxslider.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/rateit/src/rateit.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/uniform/css/uniform.default.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- Page level plugin styles END -->\r\n");
      out.write("<!-- Theme styles START -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/style-metronic.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/style.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/style-responsive.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/custom.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<!-- Theme styles END -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/jquery.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- Head END -->\r\n");
      out.write("<!-- Body BEGIN -->\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- BEGIN TOP BAR -->\r\n");
      out.write("\t<div class=\"pre-header\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!-- BEGIN TOP BAR LEFT PART -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-sm-6 additional-shop-info\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled list-inline pull-left\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/img/logo.jpg\" width=\"100px\" height=\"60px\"/></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- END TOP BAR LEFT PART -->\r\n");
      out.write("\t\t\t\t<!-- BEGIN TOP BAR MENU -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-sm-6 additional-nav\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled list-inline pull-right\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/order/showorder\">我的订单</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/userpage.jsp\">个人信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/order/showcart\">购物车</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- END TOP BAR MENU -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- BEGIN TOP SEARCH -->\r\n");
      out.write("\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<input id=\"search\" type=\"text\" size=\"35\"\r\n");
      out.write("\t\t\t\t\tstyle=\"height: 32px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button id=\"btn\" class=\"btn btn-primary\" type=\"button\">搜索</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<br> <br>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<!-- END TOP SEARCH -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- END HEADER -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- BEGIN SIDEBAR & CONTENT -->\r\n");
      out.write("\t<div class=\"row margin-bottom-40\">\r\n");
      out.write("\t\t<!-- BEGIN SIDEBAR -->\r\n");
      out.write("\t\t<div class=\"sidebar col-md-3 col-sm-5\">\r\n");
      out.write("\t\t\t<ul class=\"list-group margin-bottom-25 sidebar-menu\">\r\n");
      out.write("\t\t\t\t<li class=\"list-group-item clearfix\"><a href=\"#\" id=\"a1\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-angle-right\"></i> 手机</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"list-group-item clearfix\"><a href=\"#\" id=\"a2\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-angle-right\"></i> 电脑</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"list-group-item clearfix\"><a href=\"#\" id=\"a3\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-angle-right\"></i> 服装</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"list-group-item clearfix\"><a href=\"#\" id=\"a4\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-angle-right\"></i> 图书</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"list-group-item clearfix\"><a href=\"#\" id=\"a5\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-angle-right\"></i> 食品</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END SIDEBAR -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("              $(function(){\r\n");
      out.write("            \t  var para={\"category\":\"phone\"};\r\n");
      out.write("                      $.ajax({                           \t  \r\n");
      out.write("                          url: ' ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/showgoods',                      \r\n");
      out.write("                          type: 'POST',                  \r\n");
      out.write("                          data: para,                  \r\n");
      out.write("                          success: function (goods) {\r\n");
      out.write("                        \t\r\n");
      out.write("                        \tvar products=\"\";\r\n");
      out.write("                        \tfor(i in goods){\r\n");
      out.write("                        \t\tvar product='<div class=\"col-md-4 col-sm-6 col-xs-12\"><div class=\"product-item\"><div class=\"pi-img-wrapper\">  <img  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/img/'+goods[i].photo+'\" width=\"200px\" height=\"200px\" class=\"img-responsive\" ></div> <h3>'+goods[i].name+'</h3><div class=\"pi-price\">'+goods[i].price+'</div> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/detail?goodsID='+goods[i].goodsId+'\" class=\"btn btn-default add2cart\">查看</a></div> </div>';\r\n");
      out.write("                        \t\tproducts=products+product;\r\n");
      out.write("                        \t}\r\n");
      out.write("                        \tdocument.getElementById(\"productlist\").innerHTML=products;\r\n");
      out.write("                        \t}              \r\n");
      out.write("                       });    \r\n");
      out.write("                      $(\"#a1\").click(function(){\r\n");
      out.write("                    \t  var para={\"category\":\"phone\"};\r\n");
      out.write("                    \t  $.ajax({                           \t  \r\n");
      out.write("                              url: ' ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/showgoods',                      \r\n");
      out.write("                              type: 'POST',                  \r\n");
      out.write("                              data: para,                  \r\n");
      out.write("                              success: function (goods) {\r\n");
      out.write("                            \t\r\n");
      out.write("                            \tvar products=\"\";\r\n");
      out.write("                            \tfor(i in goods){\r\n");
      out.write("                            \t\tvar product='<div class=\"col-md-4 col-sm-6 col-xs-12\"><div class=\"product-item\"><div class=\"pi-img-wrapper\">  <img  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/img/'+goods[i].photo+'\" width=\"200px\" height=\"200px\" class=\"img-responsive\" ></div> <h3>'+goods[i].name+'</h3><div class=\"pi-price\">'+goods[i].price+'</div> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/detail?goodsID='+goods[i].goodsId+'\" class=\"btn btn-default add2cart\">查看</a></div> </div>';\r\n");
      out.write("                            \t\tproducts=products+product;\r\n");
      out.write("                            \t}\r\n");
      out.write("                            \tdocument.getElementById(\"productlist\").innerHTML=products;\r\n");
      out.write("                            \t}              \r\n");
      out.write("                      });\t  \r\n");
      out.write("                      });\r\n");
      out.write("                      \r\n");
      out.write("                      $(\"#a2\").click(function(){\r\n");
      out.write("                    \t \r\n");
      out.write("                    \t  var para={\"category\":\"computer\"};\r\n");
      out.write("                    \t  $.ajax({                           \t  \r\n");
      out.write("                              url: ' ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/showgoods',                      \r\n");
      out.write("                              type: 'POST',                  \r\n");
      out.write("                              data: para,                  \r\n");
      out.write("                              success: function (goods) {\r\n");
      out.write("                            \t\r\n");
      out.write("                            \tvar products=\"\";\r\n");
      out.write("                            \tfor(i in goods){\r\n");
      out.write("                            \t\tvar product='<div class=\"col-md-4 col-sm-6 col-xs-12\"><div class=\"product-item\"><div class=\"pi-img-wrapper\">  <img  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/img/'+goods[i].photo+'\" width=\"200px\" height=\"200px\" class=\"img-responsive\" ></div> <h3>'+goods[i].name+'</h3><div class=\"pi-price\">'+goods[i].price+'</div> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/detail?goodsID='+goods[i].goodsId+'\" class=\"btn btn-default add2cart\">查看</a></div> </div>';\r\n");
      out.write("                            \t\tproducts=products+product;\r\n");
      out.write("                            \t}\r\n");
      out.write("                            \tdocument.getElementById(\"productlist\").innerHTML=products;\r\n");
      out.write("                            \t}              \r\n");
      out.write("                      });\r\n");
      out.write("                    \t  \r\n");
      out.write("                      });\r\n");
      out.write("                      \r\n");
      out.write("                      $(\"#a3\").click(function(){\r\n");
      out.write("                    \t  var para={\"category\":\"clothes\"};\r\n");
      out.write("                    \t  $.ajax({                           \t  \r\n");
      out.write("                              url: ' ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/showgoods',                      \r\n");
      out.write("                              type: 'POST',                  \r\n");
      out.write("                              data: para,                  \r\n");
      out.write("                              success: function (goods) {\r\n");
      out.write("                            \t\r\n");
      out.write("                            \tvar products=\"\";\r\n");
      out.write("                            \tfor(i in goods){\r\n");
      out.write("                            \t\tvar product='<div class=\"col-md-4 col-sm-6 col-xs-12\"><div class=\"product-item\"><div class=\"pi-img-wrapper\">  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/img/'+goods[i].photo+'\" width=\"200px\" height=\"200px\" class=\"img-responsive\" ></div> <h3>'+goods[i].name+'</h3><div class=\"pi-price\">'+goods[i].price+'</div> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/detail?goodsID='+goods[i].goodsId+'\" class=\"btn btn-default add2cart\">查看</a></div> </div>';\r\n");
      out.write("                            \t\tproducts=products+product;\r\n");
      out.write("                            \t}\r\n");
      out.write("                            \tdocument.getElementById(\"productlist\").innerHTML=products;\r\n");
      out.write("                            \t}              \r\n");
      out.write("                      });\r\n");
      out.write("                    \t  \r\n");
      out.write("                      });\r\n");
      out.write("                      \r\n");
      out.write("                      $(\"#a4\").click(function(){\r\n");
      out.write("                    \t  var para={\"category\":\"book\"};\r\n");
      out.write("                    \t  $.ajax({                           \t  \r\n");
      out.write("                              url: ' ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/showgoods',                      \r\n");
      out.write("                              type: 'POST',                  \r\n");
      out.write("                              data: para,                  \r\n");
      out.write("                              success: function (goods) {\r\n");
      out.write("                            \t\r\n");
      out.write("                            \tvar products=\"\";\r\n");
      out.write("                            \tfor(i in goods){\r\n");
      out.write("                            \t\tvar product='<div class=\"col-md-4 col-sm-6 col-xs-12\"><div class=\"product-item\"><div class=\"pi-img-wrapper\">  <img  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/img/'+goods[i].photo+'\"  width=\"200px\" height=\"200px\" class=\"img-responsive\" ></div> <h3>'+goods[i].name+'</h3><div class=\"pi-price\">'+goods[i].price+'</div> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/detail?goodsID='+goods[i].goodsId+'\" class=\"btn btn-default add2cart\">查看</a></div> </div>';\r\n");
      out.write("                            \t\tproducts=products+product;\r\n");
      out.write("                            \t}\r\n");
      out.write("                            \tdocument.getElementById(\"productlist\").innerHTML=products;\r\n");
      out.write("                            \t}              \r\n");
      out.write("                      });\r\n");
      out.write("                    \t  \r\n");
      out.write("                      });\r\n");
      out.write("                      \r\n");
      out.write("                      $(\"#a5\").click(function(){\r\n");
      out.write("                    \t  var para={\"category\":\"food\"};\r\n");
      out.write("                    \t  $.ajax({                           \t  \r\n");
      out.write("                              url: ' ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/showgoods',                      \r\n");
      out.write("                              type: 'POST',                  \r\n");
      out.write("                              data: para,                  \r\n");
      out.write("                              success: function (goods) {\r\n");
      out.write("                            \t\r\n");
      out.write("                            \tvar products=\"\";\r\n");
      out.write("                            \tfor(i in goods){\r\n");
      out.write("                            \t\tvar product='<div class=\"col-md-4 col-sm-6 col-xs-12\"><div class=\"product-item\"><div class=\"pi-img-wrapper\">  <img  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/img/'+goods[i].photo+'\" width=\"200px\" height=\"200px\" class=\"img-responsive\" ></div> <h3>'+goods[i].name+'</h3><div class=\"pi-price\">'+goods[i].price+'</div> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/detail?goodsID='+goods[i].goodsId+'\" class=\"btn btn-default add2cart\">查看</a></div> </div>';\r\n");
      out.write("                            \t\tproducts=products+product;\r\n");
      out.write("                            \t}\r\n");
      out.write("                            \tdocument.getElementById(\"productlist\").innerHTML=products;\r\n");
      out.write("                            \t}              \r\n");
      out.write("                      });\r\n");
      out.write("                    \t  \r\n");
      out.write("                      });\r\n");
      out.write("                      \r\n");
      out.write("                      $(\"#btn\").click(function(){\r\n");
      out.write("                    \t  \r\n");
      out.write("                    \t  var para={\"name\":document.getElementById('search').value};\r\n");
      out.write("                    \t \r\n");
      out.write("                    \t  $.ajax({                           \t  \r\n");
      out.write("                              url: ' ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/search',                      \r\n");
      out.write("                              type: 'POST',                  \r\n");
      out.write("                              data: para,                  \r\n");
      out.write("                              success: function (goods) {\r\n");
      out.write("                            \t\r\n");
      out.write("                            \tvar products=\"\";\r\n");
      out.write("                            \tfor(i in goods){\r\n");
      out.write("                            \t\tvar product='<div class=\"col-md-4 col-sm-6 col-xs-12\"><div class=\"product-item\"><div class=\"pi-img-wrapper\">  <img  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/img/'+goods[i].photo+'\" width=\"200px\" height=\"200px\" class=\"img-responsive\" ></div> <h3>'+goods[i].name+'</h3><div class=\"pi-price\">'+goods[i].price+'</div> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/detail?goodsID='+goods[i].goodsId+'\" class=\"btn btn-default add2cart\">查看</a></div> </div>';\r\n");
      out.write("                            \t\tproducts=products+product;\r\n");
      out.write("                            \t}\r\n");
      out.write("                            \tdocument.getElementById(\"productlist\").innerHTML=products;\r\n");
      out.write("                            \t}              \r\n");
      out.write("                      });\r\n");
      out.write("                    \t  \r\n");
      out.write("                      });\r\n");
      out.write("                      \r\n");
      out.write("            \t  });\r\n");
      out.write("            \r\n");
      out.write("            </script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- BEGIN CONTENT -->\r\n");
      out.write("\t\t<div class=\"col-md-9 col-sm-7\">\r\n");
      out.write("\t\t\t<!-- BEGIN PRODUCT LIST -->\r\n");
      out.write("\t\t\t<div id=\"productlist\" class=\"row product-list\"></div>\r\n");
      out.write("\t\t\t<!-- END PRODUCT LIST -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END CONTENT -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END SIDEBAR & CONTENT -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- BEGIN STEPS -->\r\n");
      out.write("\t<div class=\"steps3 steps3red\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 steps3-col\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-gift\"></i>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<h2>选择商品</h2>\r\n");
      out.write("\t\t\t\t\t\t<em>加入购物车</em>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span>&nbsp;</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 steps3-col\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-gift\"></i>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<h2>选择分期</h2>\r\n");
      out.write("\t\t\t\t\t\t<em>0首付</em>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span>&nbsp;</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 steps3-col\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-truck\"></i>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<h2>送货上门</h2>\r\n");
      out.write("\t\t\t\t\t\t<em>您的满意是我们最大的荣幸</em>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- END STEPS -->\r\n");
      out.write("<!-- BEGIN PRE-FOOTER -->\r\n");
      out.write("<div class=\"pre-footer\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<!-- BEGIN BOTTOM ABOUT BLOCK -->\r\n");
      out.write("\t\t\t<div class=\"col-md-3 col-sm-6 pre-footer-col\" style=\"font-size:17px\">\r\n");
      out.write("\t\t\t\t<h2>关于我们</h2>\r\n");
      out.write("\t\t\t\t<p>我们趣分期是以服务大学生、方便大学生购物为基本宗旨的 ，在这里你可以不花一分钱就买到自己心仪已久的宝贝，还在等什么呢</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- END BOTTOM ABOUT BLOCK -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- BEGIN BOTTOM CONTACTS -->\r\n");
      out.write("\t\t\t<div class=\"col-md-3 col-sm-6 pre-footer-col\" style=\"margin-left:450px\">\r\n");
      out.write("\t\t\t\t<h2>联系我们</h2>\r\n");
      out.write("\t\t\t\t<address class=\"margin-bottom-40\">\r\n");
      out.write("\t\t\t\t\t上海市闵行区<br>\r\n");
      out.write("\t\t\t\t\t东川路800号<br>\r\n");
      out.write("\t\t\t\t\t电话: 021-12345555<br>\r\n");
      out.write("\t\t\t\t\t邮箱: 12345678@163.com<br>\r\n");
      out.write("\t\t\t\t</address>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- END BOTTOM CONTACTS -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END PRE-FOOTER -->\r\n");
      out.write("<!-- BEGIN FOOTER -->\r\n");
      out.write("<div class=\"footer padding-top-15\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<!-- BEGIN COPYRIGHT -->\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-sm-6 padding-top-10\" style=\"text-align:center;margin-left:330px\">\r\n");
      out.write("\t\t\t\t2016 @Copyright Reserved\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- END COPYRIGHT -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END FOOTER -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Load javascripts at bottom, this will reduce page load time -->\r\n");
      out.write("\t<!-- BEGIN CORE PLUGINS(REQUIRED FOR ALL PAGES) -->\r\n");
      out.write("\t<!--[if lt IE 9]>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/jquery-1.10.2.min.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/jquery-migrate-1.2.1.min.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/bootstrap/js/bootstrap.min.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/back-to-top.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/jQuery-slimScroll/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("\t<!-- END CORE PLUGINS -->\r\n");
      out.write("\t<!-- BEGIN PAGE LEVEL JAVASCRIPTS(REQUIRED ONLY FOR CURRENT PAGE) -->\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/fancybox/source/jquery.fancybox.pack.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/bxslider/jquery.bxslider.min.js\"></script>\r\n");
      out.write("\t<!-- slider for products -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/rateit/src/jquery.rateit.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/zoom/jquery.zoom.min.js'></script>\r\n");
      out.write("\t<!-- product zoom -->\r\n");
      out.write("\t<script src=\"http://code.jquery.com/ui/1.10.3/jquery-ui.js\"></script>\r\n");
      out.write("\t<!-- for slider-range -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/uniform/jquery.uniform.min.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<!-- Quantity -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/scripts/app.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("jQuery(document).ready(function() {\r\n");
      out.write("App.init();\r\n");
      out.write("App.initBxSlider();\r\n");
      out.write("App.initImageZoom();\r\n");
      out.write("App.initSliderRange();\r\n");
      out.write("App.initUniform();\r\n");
      out.write("App.initTouchspin();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\t<!-- END PAGE LEVEL JAVASCRIPTS -->\r\n");
      out.write("</body>\r\n");
      out.write("<!-- END BODY -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /index.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /index.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /index.jsp(67,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope!=null && sessionScope.userName!=null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<li>欢迎，");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</li>\r\n");
        out.write("\t\t\t\t\t\t\t<li><a href='");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/base/logout'>退出</a></li>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /index.jsp(71,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope==null ||sessionScope.userName==null }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<li><a href='");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("/login.jsp'>登录</a></li>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
