/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-07-21 01:44:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<title>登录</title>\r\n");
      out.write(" <link href=\"http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write(" <script src=\"http://libs.baidu.com/jquery/2.0.0/jquery.min.js\"></script>\r\n");
      out.write(" <script src=\"http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/messages_zh.js\"></script> \r\n");
      out.write("\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.10.4/jquery-ui.js\"></script> \r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("html,body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write(".box {\r\n");
      out.write("\tfilter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#6699FF', endColorstr='#6699FF'); /*  IE */\r\n");
      out.write("\tbackground-image:linear-gradient(bottom, #6699FF 0%, #6699FF 100%);\r\n");
      out.write("\tbackground-image:-o-linear-gradient(bottom, #6699FF 0%, #6699FF 100%);\r\n");
      out.write("\tbackground-image:-moz-linear-gradient(bottom, #6699FF 0%, #6699FF 100%);\r\n");
      out.write("\tbackground-image:-webkit-linear-gradient(bottom, #6699FF 0%, #6699FF 100%);\r\n");
      out.write("\tbackground-image:-ms-linear-gradient(bottom, #6699FF 0%, #6699FF 100%);\r\n");
      out.write("\t\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write(".login-box {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmax-width:500px;\r\n");
      out.write("\theight: 400px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\r\n");
      out.write("\tmargin-top: -200px;\r\n");
      out.write("\t/*设置负值，为要定位子盒子的一半高度*/\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("@media screen and (min-width:500px){\r\n");
      out.write("\t.login-box {\r\n");
      out.write("\t\tleft: 50%;\r\n");
      out.write("\t\t/*设置负值，为要定位子盒子的一半宽度*/\r\n");
      out.write("\t\tmargin-left: -250px;\r\n");
      out.write("\t}\r\n");
      out.write("}\t\r\n");
      out.write("\r\n");
      out.write(".form {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmax-width:500px;\r\n");
      out.write("\theight: 275px;\r\n");
      out.write("\tmargin: 25px auto 0px auto;\r\n");
      out.write("\tpadding-top: 25px;\r\n");
      out.write("}\t\r\n");
      out.write(".login-content {\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmax-width:500px;\r\n");
      out.write("\tbackground-color: rgba(255, 250, 2550, .6);\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(".input-group {\r\n");
      out.write("\tmargin: 0px 0px 30px 0px !important;\r\n");
      out.write("}\r\n");
      out.write(".form-control,\r\n");
      out.write(".input-group {\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group {\r\n");
      out.write("\tmargin-bottom: 0px !important;\r\n");
      out.write("}\r\n");
      out.write(".login-title {\r\n");
      out.write("\tpadding: 20px 10px;\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, .6);\r\n");
      out.write("}\r\n");
      out.write(".login-title h1 {\r\n");
      out.write("\tmargin-top: 10px !important;\r\n");
      out.write("}\r\n");
      out.write(".login-title small {\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".link p {\r\n");
      out.write("\tline-height: 20px;\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write(".btn-sm {\r\n");
      out.write("\tpadding: 8px 24px !important;\r\n");
      out.write("\tfont-size: 16px !important;\r\n");
      out.write("}\r\n");
      out.write("</style> \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write(" function GetQueryString(name)\r\n");
      out.write(" {\r\n");
      out.write("      var reg = new RegExp(\"(^|&)\"+ name +\"=([^&]*)(&|$)\");\r\n");
      out.write("      var r = window.location.search.substr(1).match(reg);\r\n");
      out.write("      if(r!=null)return  unescape(r[2]); return null;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("$(function(){\r\n");
      out.write("  $(\"#form\").validate({ errorPlacement: function (error, element) {\r\n");
      out.write("\t                     if (element.parent().hasClass(\"input-group\")) {\r\n");
      out.write("\t\t                           element.parent().after(error);\r\n");
      out.write("\t\t                      }\r\n");
      out.write("\t\t                     else\r\n");
      out.write("\t\t                          element.after(error)\r\n");
      out.write("\t\t                  }\r\n");
      out.write("\t\t               });\r\n");
      out.write("  if(GetQueryString(\"msg\")!=null && GetQueryString(\"msg\")!=\"\") {\r\n");
      out.write("\t  var message=GetQueryString(\"msg\");\r\n");
      out.write("\tif(message==\"ok\"){\r\n");
      out.write("\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/index.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\telse if(message==\"admin\"){\r\n");
      out.write("\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\t$(\"#btn\").click();\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t}\r\n");
      out.write("  }   \r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<button id=\"btn\" class=\"btn btn-primary btn-lg\" data-toggle=\"modal\" \r\n");
      out.write("   data-target=\"#myModal\" style=\"display:none;\"></button>\r\n");
      out.write(" <div class=\"box\">\r\n");
      out.write("\t\t<div class=\"login-box\">\r\n");
      out.write("\t\t\t<div class=\"login-title text-center\">\r\n");
      out.write("\t\t\t\t<h1><small>登录</small></h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"login-content \">\r\n");
      out.write("\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t<form id=\"form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base/login\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12  \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"userName\" name=\"userName\" class=\"form-control\" placeholder=\"用户名\" required=true>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12  \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<span  class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" placeholder=\"密码\" required=true>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group form-actions\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 col-xs-offset-4 \">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-sm btn-info\"><span class=\"glyphicon glyphicon-off\"></span> 登录</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12 link \">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-center remove-margin\" ><small>还没注册?</small> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/register.jsp\" ><small>注册</small></a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\"  tabindex=\"-1\" role=\"dialog\" \r\n");
      out.write("   aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("   <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\" style=\"margin-top:200px\">\r\n");
      out.write("         <div class=\"modal-header\">\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" \r\n");
      out.write("               aria-hidden=\"true\">×\r\n");
      out.write("            </button>\r\n");
      out.write("            <h4 class=\"modal-title\" id=\"myModalLabel\">\r\n");
      out.write("            登录失败\r\n");
      out.write("            </h4>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"modal-body\">\r\n");
      out.write("            请检查用户名和密码是否正确!\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"modal-footer\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" \r\n");
      out.write("               data-dismiss=\"modal\">关闭\r\n");
      out.write("            </button>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div><!-- /.modal-content -->\r\n");
      out.write("   </div><!-- /.modal-dialog -->\r\n");
      out.write("</div><!-- /.modal -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /login.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /login.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
